name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      uses:docker/login-action@v2
      with:
        username: ${{ secerts.DOCKER_USERNAME }}
        password: ${{ secerts.DOCKER_PASSWORD }}
    - name : build docker image
      run: docker build -t ishaniruh/node-app:latest .
    - name: push docker image in docker hub
      run: docker push ishaniruh/node-app:latest
